/**
 * All PDF text extraction goes through pdfjs-dist (the actively-maintained
 * library — also already needed for positional/table extraction). An
 * earlier version of this module used `pdf-parse` for flat text, but its
 * bundled pdf.js (v1.10.100, circa 2018) throws "bad XRef entry" on PDFs
 * generated by modern writers like pdfkit even though they're valid —
 * confirmed by reading the same file successfully with pdfjs-dist directly.
 * Dropped `pdf-parse` entirely rather than keep two parsing libraries.
 */
async function loadDocument(buffer) {
  const pdfjsLib = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const loadingTask = pdfjsLib.getDocument({
    data: new Uint8Array(buffer),
    useSystemFonts: true,
    disableFontFace: true,
    verbosity: 0,
  });
  return loadingTask.promise;
}

/**
 * Extracts three views of the document from a single load:
 *
 *  - `fullText` - whole-document flat text, for regex label matching.
 *  - `pageTexts` - the same per page, so a matched field can be attributed
 *    to the page it was found on. Each page's items are joined in reading
 *    order - pdfjs-dist returns them in content-stream order, which for
 *    pdfkit's (and most real insurers') top-to-bottom single-column
 *    layouts already matches visual reading order.
 *  - `pageItems` - every text item together with the x/y it was drawn at.
 *    Reading order is enough for "label then value" pairs, but it flattens
 *    a table: a cell that wraps onto a second line becomes an item
 *    indistinguishable from the next row's first cell, so a parser counting
 *    cells forward from an anchor silently walks off by one from there on.
 *    The coordinates say which column and which row an item really belonged
 *    to, which is what table.js rebuilds the row out of.
 */
async function extractPages(buffer) {
  const doc = await loadDocument(buffer);
  const pageTexts = [];
  const pageItems = [];

  for (let pageNum = 1; pageNum <= doc.numPages; pageNum++) {
    const page = await doc.getPage(pageNum);
    const content = await page.getTextContent();
    const text = content.items.map((item) => item.str).join('\n');
    pageTexts.push(text);
    pageItems.push(
      content.items
        .filter((item) => item.str && item.str.trim())
        .map((item) => ({
          str: item.str.trim(),
          x: item.transform[4],
          y: item.transform[5],
          width: item.width || 0,
        })),
    );
  }

  return {
    fullText: pageTexts.join('\n'), pageTexts, pageItems, numPages: doc.numPages,
  };
}

/** Which page (1-indexed) a label first appears on, or null if not found on any page. */
function pageContaining(pageTexts, label) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(escaped, 'i');
  for (let i = 0; i < pageTexts.length; i++) {
    if (pattern.test(pageTexts[i])) return i + 1;
  }
  return null;
}

/**
 * Page-by-page positional rows: buckets each page's text items by rounded
 * y-coordinate into "rows," sorted left-to-right by x. Adapted from
 * insurance-parser-node-code/src/lib/pdf.js's approach for rebuilding
 * table-shaped content that flat text would otherwise flatten out of
 * order. Not the primary extraction path — the format parsers under
 * formats/ read values positionally from the ordered line array instead,
 * which handles the real schedules seen so far. Kept as the escape hatch
 * for a layout where line order alone is genuinely ambiguous (e.g. true
 * multi-column text). Never throws: returns [] on any failure so a
 * positional-parsing problem can't take down the primary extraction.
 */
async function extractPositionalRows(buffer) {
  try {
    const doc = await loadDocument(buffer);
    const pages = [];

    for (let pageNum = 1; pageNum <= doc.numPages; pageNum++) {
      const page = await doc.getPage(pageNum);
      const content = await page.getTextContent();

      const buckets = new Map();
      for (const item of content.items) {
        if (!item.str || !item.str.trim()) continue;
        const y = Math.round(item.transform[5]);
        const x = item.transform[4];
        if (!buckets.has(y)) buckets.set(y, []);
        buckets.get(y).push({ x, text: item.str });
      }

      const rows = Array.from(buckets.entries())
        .sort(([yA], [yB]) => yB - yA)
        .map(([, items]) => items.sort((a, b) => a.x - b.x).map((i) => i.text));

      pages.push({ pageNumber: pageNum, rows });
    }

    return pages;
  } catch {
    return [];
  }
}

module.exports = { extractPages, pageContaining, extractPositionalRows };
